# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- sub-pages
- archives

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Microservices Conference" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/images/microservices.svg" # Site logo, also used in jekyll-seo-tag
description: "Academia meets Industry" # Site description and default description, also used in jekyll-seo-tag
url: "http://conf-micro.services" # Site url, also used in jekyll-seo-tag
email: "microservices@sdu.dk"
disqus: "alembic-1"
avatarurl: "/assets/images/favicon.ico" # Uses avatars for favicons to get multiple sites, eg Gravatar, Twitter, GitHub
# header_left: |
#   <a style="color:inherit; text-decoration: none !important;" href="/"><h2>
#   <img style="width: 50px; padding-bottom: 5px;" src="/assets/images/microservices.svg" alt="">
#   Microservices</h2></a>
# header_right: |
#   <p style="margin-top: 10px; margin-bottom: -5px;">Odense</p>
#   <p>25-26 Oct. 2017</p>


# 8. Site navigation
navigation_header:
  Home: /
  Contacts: /contacts/

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ""
